db:
  user: "usdf"
  passwordkey: "oods-password"
  host: "usdf-summitdb.slac.stanford.edu"
  database: "exposurelog"
hinfo:
  latiss:
    enable: false
    tag: "24.10.1"
  lsstcomcam:
    enable: false
    tag: "24.10.1"
  lsstcam:
    enable: false
    tag: "24.10.1"
pq:
  image:
    tag: "24.10.1"
