image:
  pullPolicy: Always

config:
  dp02ClientServerIsDefault: true
  dp02PostgresUri: postgresql://butler@10.161.0.4:5432/dp02
  s3EndpointUrl: "https://storage.googleapis.com"
  repositories:
    dp02: "file:///opt/lsst/butler/config/dp02.yaml"
