ingress-nginx:
  controller:
    kind: DaemonSet
    config:
      use-proxy-protocol: "false"
      enable-health-monitor: "false"
    service:
      loadBalancerIP: "10.0.1.80"
    extraArgs:
      default-ssl-certificate: ingress-nginx/ingress-certificate
vaultCertificate:
  enabled: true
