controller:
  config:
    images:
      source:
        type: "docker"
        registry: "registry-1.docker.io"
        repository: "lsstsqre/sciplat-lab"
      numReleases: 0
      numWeeklies: 0
      numDailies: 0
      pin:
        - "r29_2_0_rsp2697"
        # - "r30_0_7_rsp2827"
        # - "r30_0_6_rsp2783"
        # - "w_2026_19"
        # - "w_2026_18"
        # - "d_2026_05_20"
        # - "d_2026_05_17"
        # - "recommended"
        # - "latest_weekly"
        # - "latest_daily"
    lab:
      # env:
      #   PGPASSFILE: "/opt/lsst/software/jupyterlab/secrets/postgres-credentials.txt"
      #   PGUSER: "lsstprod_ro"
      #   NO_ACTIVITY_TIMEOUT: "432000"
      #   CULL_KERNEL_IDLE_TIMEOUT: "432000"
      #   CULL_TERMINAL_INACTIVE_TIMEOUT: "432000"
      #   DAF_BUTLER_REPOSITORY_INDEX: "/pbs/throng/lsst/software/rsp/butler-repos.yaml"
      homedirSchema: "initialThenUsername"
      homedirPrefix: "/home"
      homedirSuffix: "rsp-home"
      secrets:
        - secretName: "nublado-lab-secret"
          secretKey: "postgres-credentials.txt"
      sizes:
        - size: "small"
          cpu: 2.0
          memory: "8Gi"
        - size: "medium"
          cpu: 4.0
          memory: "16Gi"
        - size: "large"
          cpu: 8.0
          memory: "32Gi"
      volumes:
        - name: "rsp-home"
          source:
            type: "persistentVolumeClaim"
            storageClassName: "rsp-home"
            accessModes:
              - "ReadWriteMany"
            resources:
              requests:
                storage: "1Gi"
      volumeMounts:
        - containerPath: "/home"
          volumeName: "rsp-home"
hub:
  timeout:
    startup: 300

proxy:
  ingress:
    annotations:
      # proxy-body-size is temporary until USDF uses our normal ingress-nginx,
      # which already configures a larger value.
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"

jupyterhub:
  prePuller:
    continuous:
      enabled: true
  hub:
    db:
      url: "postgresql://nublado3@postgres.postgres/nublado3"
      upgrade: true
  cull:
    timeout: 432000  # 5 days
    maxAge: 691200  # 8 days
