cadc-tap:
  tapSchema:
    image:
      repository: "stvoutsin/tap-schema-roe"
      tag: 2.3.0

  config:
    gcsBucket: "lsstrsp:async-results.lsst.codes"
    gcsBucketUrl: "https://ccs3rubin.in2p3.fr:8080"
    gcsBucketType: "S3"
    datalinkPayloadUrl: "https://github.com/gabrimaine/sdm_schemas/releases/download/2.4.1/datalink-snippets.zip"

    qserv:
      host: "192.41.122.85:30040"
