prompt-proto-service:

  podAnnotations:
    # HACK: disable autoscaling as workaround for DM-41829
    autoscaling.knative.dev/min-scale: "20"
    autoscaling.knative.dev/max-scale: "20"
    # Update this field if using latest or static image tag in dev
    revision: "1"

  # HACK: disable autoscaling as workaround for DM-41829
  worker:
    restart: 15

  image:
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 4.7.1

  instrument:
    pipelines:
      # BLOCK-T60 is optics alignment
      # BLOCK-T75 is giant donuts
      # BLOCK-T88 is optics alignment
      # BLOCK-T246 is instrument checkout
      # BLOCK-T249 is AOS alignment
      main: >-
        (survey="PP-SURVEY")=[${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCam/ApPipe.yaml,
        ${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCam/SingleFrame.yaml,
        ${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCam/Isr.yaml]
        (survey="BLOCK-T60")=[${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCam/Isr-cal.yaml]
        (survey="BLOCK-T75")=[]
        (survey="BLOCK-T88")=[${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCam/Isr-cal.yaml]
        (survey="BLOCK-T246")=[${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCam/Isr-cal.yaml]
        (survey="BLOCK-T249")=[${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCam/Isr-cal.yaml]
        (survey="")=[]
      preprocessing: >-
        (survey="PP-SURVEY")=[${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCam/Preprocessing.yaml]
        (survey="BLOCK-T60")=[]
        (survey="BLOCK-T75")=[]
        (survey="BLOCK-T88")=[]
        (survey="BLOCK-T246")=[]
        (survey="BLOCK-T249")=[]
        (survey="")=[]
    calibRepo: s3://rubin-summit-users

  s3:
    imageBucket: rubin-summit
    endpointUrl: https://sdfembs3.sdf.slac.stanford.edu

  raw_microservice: http://172.24.5.158:8080/presence

  imageNotifications:
    kafkaClusterAddress: prompt-processing-2-kafka-bootstrap.kafka:9092
    topic: rubin-summit-notification
    # Scheduler adds an extra 60-80-second delay for first visit in a sequence,
    # and files can take up to 20 seconds to arrive. Scheduler delay associated
    # with CWFS engineering data, should not apply to other cameras.
    imageTimeout: 110

  apdb:
    config: s3://rubin-summit-users/apdb_config/cassandra/pp_apdb_lsstcomcam.py

  alerts:
    topic: "lsstcomcam-alerts"

  sasquatch:
    endpointUrl: https://usdf-rsp-dev.slac.stanford.edu/sasquatch-rest-proxy
    namespace: lsst.prompt.prod
    auth_env: false

  logLevel: timer.lsst.activator=DEBUG lsst.diaPipe=VERBOSE lsst.rbClassify=VERBOSE lsst.resources=DEBUG

  fullnameOverride: "prompt-proto-service-lsstcomcam"
