obsenv-api:
  image:
    repository: rubin-cr.lsst.org/obsenv-api
    tag: 0.1.0
    pullPolicy: Always
  config:
    logLevel: "DEBUG"
  nfsMount:
    server: nfs-obsenv.tu.lsst.org

obsenv-ui:
  image:
    repository: rubin-cr.lsst.org/obsenv-ui
    tag: 0.1.0
    pullPolicy: Always
  config:
    pathPrefix: /obsenv-management
